import { Brain, Cloud, Database, Layers, MapPin, RefreshCw, Wrench, type LucideIcon } from "lucide-react";

// Shared between the rotating FlashCards widget and the About page — single source of truth so
// the two never drift apart into inconsistent claims about what the app actually does.
export type Fact = {
  icon: LucideIcon;
  title: string;
  tag: string;
  description: string;
};

export const APP_FACTS: Fact[] = [
  {
    icon: Brain,
    title: "Open-source LLM",
    tag: "Groq · gpt-oss-120b",
    description:
      "Answers are generated by an open-weight model served free via Groq — zero OpenAI or Anthropic dependency anywhere in this stack.",
  },
  {
    icon: MapPin,
    title: "Timestamp citations",
    tag: "Grounded answers",
    description:
      "Every answer links back to the exact moment in the video it came from — click a citation, jump straight there.",
  },
  {
    icon: RefreshCw,
    title: "Conversational memory",
    tag: "Sliding-window STM",
    description:
      "Follow-up questions with pronouns (\"what about that?\") resolve correctly against your last few turns.",
  },
  {
    icon: Layers,
    title: "Multi-session chats",
    tag: "Up to 3 at once",
    description:
      "Juggle up to three videos in parallel, each with its own history, persisted locally between visits.",
  },
  {
    icon: Database,
    title: "Pinecone vector search",
    tag: "Hosted embeddings",
    description:
      "Transcripts are chunked, embedded, and retrieved via Pinecone's own hosted inference — no self-hosted vector infra.",
  },
  {
    icon: Cloud,
    title: "Serverless on Vercel",
    tag: "Next.js + Python",
    description:
      "A Next.js frontend and a Python (FastAPI) RAG backend, deployed together as Vercel serverless functions on the free tier.",
  },
  {
    icon: Wrench,
    title: "On the roadmap",
    tag: "Coming next",
    description:
      "Hybrid + reranked retrieval, LLM-based guardrails, and a DeepEval evaluation suite — in progress, not yet live.",
  },
];
